#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: indy-plenum
  description: Plenum Byzantine Fault Tolerant Protocol
  homepage: https://wiki.hyperledger.org/display/indy
  default_branch: master
  has_downloads: true
  has_issues: true
  has_projects: false
  has_wiki: true
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
